apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::864974731196:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1A0CXJOKRTYUQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::864974731196:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-03T01:15:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1529"
  uid: 582af121-f4e0-468c-93cf-b71effa3e2e5
